### ISSUE TITLE
UI Feature: Customizable corporate design elements

### ISSUE THREAD

**Issue by jgrieb** [DINA-Web/dina-feedback#16]
**Is your feature request related to a problem? Please describe.**
Currently, the AAFC/Canada logo have a prominent place in the UI and there is no way to replace them without creating a custom fork of `dina-ui`.

There are further UI elements or information elements which should be able to be configured by each institution hosting DINA individually. A non-exhaustive list includes:

- [Default license selected for media in the object store](https://github.com/AAFC-BICoE/object-store-api/blob/04b94df68bf5a5a912f1268cbf063a2e9d538261/src/main/resources/application.yml#L38)
- [Default copyright statement selected for media in the object store](https://github.com/AAFC-BICoE/object-store-api/blob/04b94df68bf5a5a912f1268cbf063a2e9d538261/src/main/resources/application.yml#L41)

**Describe the solution you'd like**
There should be an option to configure these institution-specific design and information elements.

**Comment by jgrieb** [comment]
Update: After an initial discussion on 07 May, we agreed to tackle first the logo issue. Next steps:

- [ ] In the dina-ui, rename references like `canadaLogo_en.svg` to more generic names
- [x] Test and document, whether the logo image can be simply replaced by running the `dina-ui` docker image with a volume overwriting the image path(s)

**Comment by jgrieb** [comment]
Update: I tested this, currently it is easy to use docker volumes to replace the header logos like in

```
volumes:
      - ./static/sgn-logo.png:/www/html/static/images/canadaLogo_en.svg:ro
      - ./static/sgn-logo.png:/www/html/static/images/canadaLogo_de.svg:ro
```

However, it only works for the volume in the header. The one in the footer is currently included in a link. Therefore next steps are:

- [ ] In dina-ui, include the footer logo as a file analogously to the header logo
- [ ] In dina-ui, rename references like canadaLogo_en.svg to more generic names

However, there are many more fields which require institution specific customization like mentioned above (e.g. the license/ copyright statements), but possibly also the links in the footer ("Contact information", "Privacy", etc.) where we need a good strategy. Possibly reading these default configurations in from a JSON file, which then in production can be overwritten as a docker volume just like the logos...

**Comment by uebersee-museum** [comment]
@jgrieb - Please document the workaround (for our developer to reproduce) in the configuration to change the copyright information, thank you (discussed in our meeting on 5. November)

**Comment by cgendreau** [comment]
You can override the current values with the following:

>     environment:
>       - DEFAULT_VALUES_VALUES_0_TYPE=metadata
>       - DEFAULT_VALUES_VALUES_0_ATTRIBUTE=xmpRightsWebStatement
>       - DEFAULT_VALUES_VALUES_0_VALUE=${WEB_STATEMENT}
>       - DEFAULT_VALUES_VALUES_1_TYPE=metadata
>       - DEFAULT_VALUES_VALUES_1_ATTRIBUTE=dcRights
>       - DEFAULT_VALUES_VALUES_1_VALUE=${DC_RIGHTS}
>       - DEFAULT_VALUES_VALUES_2_TYPE=metadata
>       - DEFAULT_VALUES_VALUES_2_ATTRIBUTE=xmpRightsOwner
>       - DEFAULT_VALUES_VALUES_2_VALUE=${RIGHTS_OWNER}
>       - DEFAULT_VALUES_VALUES_3_TYPE=metadata
>       - DEFAULT_VALUES_VALUES_3_ATTRIBUTE=xmpRightsUsageTerms
>       - DEFAULT_VALUES_VALUES_3_VALUE=${USAGE_TERMS}

**Comment by jgrieb** [comment]
Hi, sorry was busy with a workshop.

Yes, like @cgendreau already posted I had found out to set these values in the `docker-compose.local.env`.

Another possible method is to use a dedicated file and mount it as a docker volume, so set in the `docker-compose` file:

```
    volumes:
      - ./config/object-store-application.yml:/config/application.yml:ro
```

And then this file may look like

```
default-values:
  values:
    - type: metadata
      attribute: xmpRightsWebStatement
      value: https://senckenberg.de/usage-terms
    - type: metadata
      attribute: dcRights
      value: "© Senckenberg Gesellschaft für Naturforschung"
    - type: metadata
      attribute: xmpRightsOwner
      value: Senckenberg Gesellschaft für Naturforschung
    - type: metadata
      attribute: xmpRightsUsageTerms
      value: Senckenberg Usage Terms
```
